sonar.projectKey=prova01-unit-mateuslealhemkemeier
sonar.organization=mateuslh
sonar.projectName=Jest Unit Test
sonar.projectVersion=1.0
sonar.sources=./src
sonar.tests=./test
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
